-- ============================================================================
-- 02 — Helper functions (claimant/host/table asserts, time, shuffle, is_admin, triggers)
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tools/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.huddle_is_claimant(p_claimed_by jsonb, p_uid text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM jsonb_each_text(COALESCE(p_claimed_by, '{}'::jsonb))
    WHERE value = p_uid
  );
$function$;

CREATE OR REPLACE FUNCTION public.huddle_assert_room_table(p_table text)
 RETURNS void
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
AS $function$
BEGIN
  IF p_table NOT IN ('hotseat_rooms', 'chameleon_rooms', 'liar_rooms', 'mafia_rooms') THEN
    RAISE EXCEPTION 'invalid_table: %', p_table USING ERRCODE = '22023';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_assert_host(p_state jsonb, p_uid text)
 RETURNS void
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
AS $function$
BEGIN
  IF (p_state->>'hostId') IS DISTINCT FROM p_uid THEN
    RAISE EXCEPTION 'not_host' USING ERRCODE = '42501';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_phase_start_ms()
 RETURNS bigint
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
  SELECT (extract(epoch FROM now()) * 1000)::bigint + 450;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_shuffle_jsonb(p_arr jsonb)
 RETURNS jsonb
 LANGUAGE sql
 PARALLEL SAFE
AS $function$
  SELECT COALESCE(jsonb_agg(elem ORDER BY random()), '[]'::jsonb)
  FROM jsonb_array_elements(p_arr) AS elem;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_assert_narrator(p_state jsonb, p_uid text)
 RETURNS void
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
AS $function$
BEGIN
  IF (p_state->>'narratorUid') IS DISTINCT FROM p_uid THEN
    RAISE EXCEPTION 'not_narrator' USING ERRCODE = '42501';
  END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select exists (
    select 1
    from public.admins a
    join auth.users   u on lower(u.email) = lower(a.email)
    where u.id = auth.uid()
  );
$function$;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.feedback_posts_touch()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;
