-- ============================================================================
-- 03 — Universal room RPCs (create / claim / leave / close / migrate seat)
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tmp/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.huddle_create_room(p_table text, p_code text, p_initial_state jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_new_state JSONB;
  v_inserted  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM public.huddle_assert_room_table(p_table);

  IF p_code IS NULL OR length(p_code) = 0 THEN
    RAISE EXCEPTION 'invalid_code' USING ERRCODE = '22023';
  END IF;
  IF p_initial_state IS NULL OR jsonb_typeof(p_initial_state) <> 'object' THEN
    RAISE EXCEPTION 'invalid_state' USING ERRCODE = '22023';
  END IF;
  IF NOT public.huddle_is_claimant(p_initial_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'creator_must_be_claimant' USING ERRCODE = '42501';
  END IF;
  IF (p_initial_state->>'hostId') IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'creator_must_be_host' USING ERRCODE = '42501';
  END IF;

  v_new_state := jsonb_set(
    p_initial_state,
    '{revision}',
    to_jsonb(COALESCE((p_initial_state->>'revision')::int, 0) + 1)
  );

  EXECUTE format(
    'INSERT INTO public.%I (code, state) VALUES ($1, $2) RETURNING state',
    p_table
  ) USING p_code, v_new_state INTO v_inserted;

  RETURN v_inserted;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_claim_seat(p_table text, p_code text, p_player_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_claimedBy JSONB;
  v_existing  TEXT;
  v_old_seat  TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM public.huddle_assert_room_table(p_table);

  IF p_player_id IS NULL OR length(p_player_id) = 0 THEN
    RAISE EXCEPTION 'invalid_player_id' USING ERRCODE = '22023';
  END IF;

  EXECUTE format('SELECT state FROM public.%I WHERE code = $1 FOR UPDATE', p_table)
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'closedByHost')::boolean IS TRUE THEN
    RAISE EXCEPTION 'room_closed' USING ERRCODE = '42501';
  END IF;

  v_claimedBy := COALESCE(v_state->'claimedBy', '{}'::jsonb);

  -- Reject if the target seat is held by someone else.
  v_existing := v_claimedBy->>p_player_id;
  IF v_existing IS NOT NULL AND v_existing <> v_uid THEN
    RAISE EXCEPTION 'seat_already_claimed' USING ERRCODE = '42501';
  END IF;

  -- NEW IN TURN 2: switch-seats support. If caller already holds a *different*
  -- seat in this room, release it before claiming the new one.
  SELECT key INTO v_old_seat
  FROM jsonb_each_text(v_claimedBy)
  WHERE value = v_uid AND key <> p_player_id
  LIMIT 1;

  IF v_old_seat IS NOT NULL THEN
    v_claimedBy := v_claimedBy - v_old_seat;
  END IF;

  -- Claim the new seat.
  v_claimedBy := jsonb_set(v_claimedBy, ARRAY[p_player_id], to_jsonb(v_uid), true);
  v_state := jsonb_set(v_state, '{claimedBy}', v_claimedBy);

  -- If host is unset, claim it.
  IF (v_state->>'hostId') IS NULL THEN
    v_state := jsonb_set(v_state, '{hostId}', to_jsonb(v_uid));
  END IF;

  -- Bump revision.
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  EXECUTE format('UPDATE public.%I SET state = $1 WHERE code = $2', p_table)
    USING v_state, p_code;

  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_leave_seat(p_table text, p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_claimedBy JSONB;
  v_my_seat   TEXT;
  v_next_host TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM public.huddle_assert_room_table(p_table);

  EXECUTE format('SELECT state FROM public.%I WHERE code = $1 FOR UPDATE', p_table)
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  v_claimedBy := COALESCE(v_state->'claimedBy', '{}'::jsonb);

  -- Find the caller's seat id (the key whose value equals my uid).
  SELECT key INTO v_my_seat
  FROM jsonb_each_text(v_claimedBy)
  WHERE value = v_uid
  LIMIT 1;

  IF v_my_seat IS NULL THEN
    -- Not seated; nothing to do. Idempotent return.
    RETURN v_state;
  END IF;

  v_claimedBy := v_claimedBy - v_my_seat;
  v_state := jsonb_set(v_state, '{claimedBy}', v_claimedBy);

  -- Host transfer: if caller was host, pick the next-lowest-seat-id holder
  -- (the client's existing rule).
  IF (v_state->>'hostId') = v_uid THEN
    SELECT value INTO v_next_host
    FROM jsonb_each_text(v_claimedBy)
    ORDER BY key
    LIMIT 1;

    IF v_next_host IS NOT NULL THEN
      v_state := jsonb_set(v_state, '{hostId}', to_jsonb(v_next_host));
    ELSE
      v_state := jsonb_set(v_state, '{hostId}', 'null'::jsonb);
    END IF;
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  EXECUTE format('UPDATE public.%I SET state = $1 WHERE code = $2', p_table)
    USING v_state, p_code;

  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_close_room(p_table text, p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid   TEXT;
  v_state JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM public.huddle_assert_room_table(p_table);

  EXECUTE format('SELECT state FROM public.%I WHERE code = $1 FOR UPDATE', p_table)
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'hostId') IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'not_host' USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{closedByHost}', 'true'::jsonb);
  v_state := jsonb_set(v_state, '{hostId}',       'null'::jsonb);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  EXECUTE format('UPDATE public.%I SET state = $1 WHERE code = $2', p_table)
    USING v_state, p_code;

  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_migrate_seat(p_table text, p_code text, p_from_session_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid            TEXT;
  v_state          JSONB;
  v_claimedBy      JSONB;
  v_phase          TEXT;
  v_old_seat       TEXT;
  v_existing_seat  TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  PERFORM public.huddle_assert_room_table(p_table);

  IF p_from_session_id IS NULL OR length(p_from_session_id) = 0 THEN
    RAISE EXCEPTION 'invalid_from_session_id' USING ERRCODE = '22023';
  END IF;

  -- Migrating from yourself to yourself is a no-op. Return current state so
  -- the caller can still use the returned JSONB if it wants to.
  IF p_from_session_id = v_uid THEN
    EXECUTE format('SELECT state FROM public.%I WHERE code = $1', p_table)
      USING p_code INTO v_state;
    RETURN v_state;
  END IF;

  EXECUTE format('SELECT state FROM public.%I WHERE code = $1 FOR UPDATE', p_table)
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'closedByHost')::boolean IS TRUE THEN
    RAISE EXCEPTION 'room_closed' USING ERRCODE = '42501';
  END IF;

  -- Lobby-only: don't allow migration mid-game. Game phases have invariants
  -- (turn order, roles, votes) tied to seat identity; rewriting claimedBy
  -- mid-game could corrupt them. If anyone signs in mid-game, they'll
  -- have to finish as-is or refresh after the round ends.
  v_phase := v_state->>'phase';
  IF v_phase IS NOT NULL AND v_phase <> 'lobby' AND v_phase <> '' THEN
    RETURN v_state;
  END IF;

  v_claimedBy := COALESCE(v_state->'claimedBy', '{}'::jsonb);

  -- Find the seat held by the old session id. If none, nothing to migrate.
  SELECT key INTO v_old_seat
  FROM jsonb_each_text(v_claimedBy)
  WHERE value = p_from_session_id
  LIMIT 1;

  IF v_old_seat IS NULL THEN
    RETURN v_state;
  END IF;

  -- Refuse if the new user (auth.uid()) already holds a DIFFERENT seat in
  -- this room. That would mean a real Google user is already seated, and
  -- migrating the from-session's seat into them would either (a) steal an
  -- innocent third-party's seat or (b) leave the new user double-claimed.
  -- Safer to silently no-op and let the user resolve manually.
  SELECT key INTO v_existing_seat
  FROM jsonb_each_text(v_claimedBy)
  WHERE value = v_uid AND key <> v_old_seat
  LIMIT 1;

  IF v_existing_seat IS NOT NULL THEN
    RETURN v_state;
  END IF;

  -- Reassign the seat to the new user.
  v_claimedBy := jsonb_set(v_claimedBy, ARRAY[v_old_seat], to_jsonb(v_uid), true);
  v_state := jsonb_set(v_state, '{claimedBy}', v_claimedBy);

  -- If the old session was the host, transfer host to the new user too.
  IF (v_state->>'hostId') = p_from_session_id THEN
    v_state := jsonb_set(v_state, '{hostId}', to_jsonb(v_uid));
  END IF;

  -- Bump revision so realtime echoes propagate to every other client.
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  EXECUTE format('UPDATE public.%I SET state = $1 WHERE code = $2', p_table)
    USING v_state, p_code;

  RETURN v_state;
END;
$function$;
