-- ============================================================================
-- 04 — Hot Seat RPCs
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tmp/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.huddle_hot_apply_recommended(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid   TEXT;
  v_state JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  v_state := v_state || jsonb_build_object(
    'mode',     'classic',
    'category', 'mixed',
    'rounds',   1,
    'order',    'rotating'
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_dismiss_splash(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_idx       INT;
  v_used      JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'phase') <> 'splash' THEN
    -- Idempotent: someone already advanced
    RETURN v_state;
  END IF;

  v_idx := COALESCE((v_state->>'currentPlayerIdx')::int, 0);
  v_used := COALESCE(v_state->'playersUsedThisRound', '[]'::jsonb);
  -- Idempotent append
  IF NOT EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_used) AS u(i)
    WHERE i::int = v_idx
  ) THEN
    v_used := v_used || to_jsonb(v_idx);
  END IF;

  v_state := v_state || jsonb_build_object(
    'playersUsedThisRound', v_used,
    'roundOutcome',         null,
    'turnStartTime',        (extract(epoch FROM now()) * 1000)::bigint,
    'phase',                'play',
    'phaseStartAt',         public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_end_round(p_code text, p_outcome text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid             TEXT;
  v_state           JSONB;
  v_my_seat         TEXT;
  v_current_idx     INT;
  v_players         JSONB;
  v_current_player  JSONB;
  v_current_pid     TEXT;
  v_duration        BIGINT;
  v_turn_start      BIGINT;
  v_player_wins     INT;
  v_player_best     BIGINT;
  v_new_players     JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_outcome NOT IN ('won', 'forfeit') THEN
    RAISE EXCEPTION 'invalid_outcome' USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'phase') <> 'play' THEN
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;

  -- Identify caller's seat
  SELECT key INTO v_my_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_seat IS NULL THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  v_current_idx := COALESCE((v_state->>'currentPlayerIdx')::int, 0);
  v_players := COALESCE(v_state->'players', '[]'::jsonb);
  v_current_player := v_players->v_current_idx;
  v_current_pid := v_current_player->>'id';

  -- Role gate: forfeit must be hot seat, won must be non-hot-seat
  IF p_outcome = 'forfeit' AND v_my_seat <> v_current_pid THEN
    RAISE EXCEPTION 'only_hotseat_can_forfeit' USING ERRCODE = '42501';
  END IF;
  IF p_outcome = 'won' AND v_my_seat = v_current_pid THEN
    RAISE EXCEPTION 'only_helper_can_mark_won' USING ERRCODE = '42501';
  END IF;

  -- Compute duration
  v_turn_start := COALESCE((v_state->>'turnStartTime')::bigint, 0);
  IF v_turn_start > 0 THEN
    v_duration := (extract(epoch FROM now()) * 1000)::bigint - v_turn_start;
  ELSE
    v_duration := 0;
  END IF;

  -- Update player.wins / bestTimeMs if won
  IF p_outcome = 'won' THEN
    v_player_wins := COALESCE((v_current_player->>'wins')::int, 0) + 1;
    v_player_best := COALESCE((v_current_player->>'bestTimeMs')::bigint, 9223372036854775807);
    IF v_duration < v_player_best THEN
      v_player_best := v_duration;
    END IF;
    v_current_player := v_current_player || jsonb_build_object(
      'wins',       v_player_wins,
      'bestTimeMs', v_player_best
    );
    v_new_players := jsonb_set(v_players, ARRAY[v_current_idx::text], v_current_player);
    v_state := jsonb_set(v_state, '{players}', v_new_players);
  END IF;

  v_state := v_state || jsonb_build_object(
    'roundOutcome',     p_outcome,
    'lastTurnDuration', v_duration,
    'phase',            'result',
    'phaseStartAt',     public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_handle_disconnect(p_code text, p_gone_session_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_gone_seat        TEXT;
  v_remaining_claim  JSONB;
  v_lowest_seat_uid  TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  SELECT key INTO v_gone_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = p_gone_session_id
  LIMIT 1;

  IF v_gone_seat IS NULL THEN
    RETURN v_state;
  END IF;

  v_remaining_claim := (v_state->'claimedBy') - v_gone_seat;
  v_state := jsonb_set(v_state, '{claimedBy}', v_remaining_claim);

  IF (v_state->>'hostId') = p_gone_session_id THEN
    SELECT value INTO v_lowest_seat_uid
    FROM jsonb_each_text(v_remaining_claim)
    ORDER BY key
    LIMIT 1;
    IF v_lowest_seat_uid IS NOT NULL THEN
      v_state := jsonb_set(v_state, '{hostId}', to_jsonb(v_lowest_seat_uid));
    ELSE
      v_state := jsonb_set(v_state, '{hostId}', 'null'::jsonb);
    END IF;
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_mark_game_counted(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_used_count       INT;
  v_claimed_count    INT;
  v_current_round    INT;
  v_rounds           INT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'phase') <> 'result' THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;
  -- Idempotent
  IF (v_state->>'_gamesPlayedCounted')::boolean IS TRUE THEN
    RETURN v_state;
  END IF;

  v_used_count := jsonb_array_length(COALESCE(v_state->'playersUsedThisRound', '[]'::jsonb));
  SELECT count(*) INTO v_claimed_count FROM jsonb_object_keys(COALESCE(v_state->'claimedBy', '{}'::jsonb));
  v_current_round := COALESCE((v_state->>'currentRound')::int, 1);
  v_rounds := COALESCE((v_state->>'rounds')::int, 1);

  IF NOT (v_used_count = v_claimed_count AND v_current_round = v_rounds) THEN
    RAISE EXCEPTION 'not_last_turn' USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{_gamesPlayedCounted}', 'true'::jsonb);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_next_turn(p_code text, p_player_idx integer, p_word text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid            TEXT;
  v_state          JSONB;
  v_used           JSONB;
  v_claimed_count  INT;
  v_players        JSONB;
  v_player_id      TEXT;
  v_claimed_by     JSONB;
  v_used_words     JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_word IS NULL OR length(trim(p_word)) = 0 THEN
    RAISE EXCEPTION 'invalid_word' USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);
  IF (v_state->>'phase') <> 'result' THEN
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;

  v_used := COALESCE(v_state->'playersUsedThisRound', '[]'::jsonb);
  v_claimed_by := COALESCE(v_state->'claimedBy', '{}'::jsonb);
  SELECT count(*) INTO v_claimed_count FROM jsonb_object_keys(v_claimed_by);

  -- Round-rollover: if all claimed players have been used, bump round & reset
  IF jsonb_array_length(v_used) >= v_claimed_count THEN
    v_state := jsonb_set(
      v_state,
      '{currentRound}',
      to_jsonb(COALESCE((v_state->>'currentRound')::int, 1) + 1)
    );
    v_state := jsonb_set(v_state, '{playersUsedThisRound}', '[]'::jsonb);
  END IF;

  -- Now start the next turn (mirrors start_turn validation)
  v_players := COALESCE(v_state->'players', '[]'::jsonb);
  IF p_player_idx < 0 OR p_player_idx >= jsonb_array_length(v_players) THEN
    RAISE EXCEPTION 'invalid_player_idx' USING ERRCODE = '22023';
  END IF;
  v_player_id := v_players->p_player_idx->>'id';
  IF (v_claimed_by->>v_player_id) IS NULL THEN
    RAISE EXCEPTION 'seat_not_claimed' USING ERRCODE = '42501';
  END IF;
  v_used := COALESCE(v_state->'playersUsedThisRound', '[]'::jsonb);
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_used) AS u(idx)
    WHERE idx::int = p_player_idx
  ) THEN
    RAISE EXCEPTION 'player_already_used_this_round' USING ERRCODE = '42501';
  END IF;

  v_used_words := COALESCE(v_state->'usedWords', '[]'::jsonb) || jsonb_build_array(p_word);

  v_state := v_state || jsonb_build_object(
    'currentPlayerIdx', p_player_idx,
    'currentWord',      p_word,
    'roundOutcome',     null,
    'phase',            'splash',
    'phaseStartAt',     public.huddle_phase_start_ms(),
    'usedWords',        v_used_words
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_play_again(p_code text, p_player_idx integer, p_word text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid           TEXT;
  v_state         JSONB;
  v_players       JSONB;
  v_player_id     TEXT;
  v_claimed_by    JSONB;
  v_used_words    JSONB;
  v_new_players   JSONB;
  v_idx           INT;
  v_p             JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_word IS NULL OR length(trim(p_word)) = 0 THEN
    RAISE EXCEPTION 'invalid_word' USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  v_players := COALESCE(v_state->'players', '[]'::jsonb);
  IF p_player_idx < 0 OR p_player_idx >= jsonb_array_length(v_players) THEN
    RAISE EXCEPTION 'invalid_player_idx' USING ERRCODE = '22023';
  END IF;
  v_player_id := v_players->p_player_idx->>'id';
  v_claimed_by := COALESCE(v_state->'claimedBy', '{}'::jsonb);
  IF (v_claimed_by->>v_player_id) IS NULL THEN
    RAISE EXCEPTION 'seat_not_claimed' USING ERRCODE = '42501';
  END IF;

  -- Reset each player's wins + bestTimeMs
  v_new_players := '[]'::jsonb;
  FOR v_idx IN 0 .. jsonb_array_length(v_players) - 1 LOOP
    v_p := v_players->v_idx;
    v_p := v_p || jsonb_build_object(
      'wins',       0,
      'bestTimeMs', null
    );
    v_new_players := v_new_players || jsonb_build_array(v_p);
  END LOOP;

  v_used_words := COALESCE(v_state->'usedWords', '[]'::jsonb) || jsonb_build_array(p_word);

  v_state := v_state || jsonb_build_object(
    'players',               v_new_players,
    'currentRound',          1,
    'playersUsedThisRound',  '[]'::jsonb,
    '_gamesPlayedCounted',   false,
    'closedByHost',          false,
    'currentPlayerIdx',      p_player_idx,
    'currentWord',           p_word,
    'roundOutcome',          null,
    'phase',                 'splash',
    'phaseStartAt',          public.huddle_phase_start_ms(),
    'usedWords',             v_used_words
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_reset_players(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_my_seat   TEXT;
  v_new_claim JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  SELECT key INTO v_my_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;

  IF v_my_seat IS NULL THEN
    v_new_claim := '{}'::jsonb;
  ELSE
    v_new_claim := jsonb_build_object(v_my_seat, v_uid);
  END IF;

  v_state := jsonb_set(v_state, '{claimedBy}', v_new_claim);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_set_setting(p_code text, p_field text, p_value jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid   TEXT;
  v_state JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  -- Allowlist the field name — prevents writing arbitrary state paths
  IF p_field NOT IN ('category', 'rounds', 'order', 'mode') THEN
    RAISE EXCEPTION 'invalid_field: %', p_field USING ERRCODE = '22023';
  END IF;

  -- Type-check the value
  IF p_field = 'rounds' THEN
    IF jsonb_typeof(p_value) <> 'number' THEN
      RAISE EXCEPTION 'rounds_must_be_number' USING ERRCODE = '22023';
    END IF;
    IF (p_value::text)::int < 1 OR (p_value::text)::int > 99 THEN
      RAISE EXCEPTION 'rounds_out_of_range' USING ERRCODE = '22023';
    END IF;
  ELSE
    IF jsonb_typeof(p_value) <> 'string' THEN
      RAISE EXCEPTION 'value_must_be_string' USING ERRCODE = '22023';
    END IF;
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  v_state := jsonb_set(v_state, ARRAY[p_field], p_value);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_hot_start_turn(p_code text, p_player_idx integer, p_word text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid           TEXT;
  v_state         JSONB;
  v_players       JSONB;
  v_player_id     TEXT;
  v_claimed_by    JSONB;
  v_used          JSONB;
  v_used_words    JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_word IS NULL OR length(trim(p_word)) = 0 THEN
    RAISE EXCEPTION 'invalid_word' USING ERRCODE = '22023';
  END IF;
  IF length(p_word) > 200 THEN
    RAISE EXCEPTION 'word_too_long' USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.hotseat_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  v_players := COALESCE(v_state->'players', '[]'::jsonb);
  IF p_player_idx < 0 OR p_player_idx >= jsonb_array_length(v_players) THEN
    RAISE EXCEPTION 'invalid_player_idx' USING ERRCODE = '22023';
  END IF;
  v_player_id := v_players->p_player_idx->>'id';
  v_claimed_by := COALESCE(v_state->'claimedBy', '{}'::jsonb);
  IF (v_claimed_by->>v_player_id) IS NULL THEN
    RAISE EXCEPTION 'seat_not_claimed' USING ERRCODE = '42501';
  END IF;
  v_used := COALESCE(v_state->'playersUsedThisRound', '[]'::jsonb);
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_used) AS u(idx)
    WHERE idx::int = p_player_idx
  ) THEN
    RAISE EXCEPTION 'player_already_used_this_round' USING ERRCODE = '42501';
  END IF;

  -- Append word to usedWords (defensive — client also tracks locally)
  v_used_words := COALESCE(v_state->'usedWords', '[]'::jsonb) || jsonb_build_array(p_word);

  v_state := v_state || jsonb_build_object(
    'currentPlayerIdx', p_player_idx,
    'currentWord',      p_word,
    'roundOutcome',     null,
    'phase',            'splash',
    'phaseStartAt',     public.huddle_phase_start_ms(),
    'usedWords',        v_used_words
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.hotseat_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;
