-- ============================================================================
-- 06 — Liar's Cup RPCs
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tmp/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.huddle_liar_after_sip(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_my_player_id     TEXT;
  v_pending_loser    TEXT;
  v_pending_cause    TEXT;
  v_pending_accuser  TEXT;
  v_alive            JSONB;
  v_accused_id       TEXT;
  v_winner_id        TEXT;
  v_outcome          TEXT;
  v_alive_count      INT;
  v_cup_spills       INT;
  v_round_count      INT;
  v_winner_idx       INT;
  v_multiplier       INT;
  v_hand_size        INT := 5;
  v_table_card       TEXT;
  v_prev_table       TEXT;
  v_deck             JSONB;
  v_hands            JSONB;
  v_player_hand      JSONB;
  v_player_id        TEXT;
  v_idx              INT;
  v_wins             JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  IF (v_state->>'phase') <> 'cup' THEN
    RETURN v_state;
  END IF;
  IF (v_state->>'sipTaken')::boolean IS NOT TRUE THEN
    RAISE EXCEPTION 'sip_not_taken' USING ERRCODE = '42501';
  END IF;

  v_pending_loser   := v_state->>'pendingLoserId';
  v_pending_cause   := v_state->>'pendingLoserCause';
  v_pending_accuser := v_state->>'pendingAccuserId';
  v_outcome         := v_state->>'sipOutcome';

  SELECT key INTO v_my_player_id
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_player_id IS DISTINCT FROM v_pending_loser THEN
    RAISE EXCEPTION 'not_loser' USING ERRCODE = '42501';
  END IF;

  v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
  v_accused_id := v_state->'lastPlay'->>'byPlayerId';

  -- NEW: winner of LIAR call uses the stored accuser, not currentPlayerIdx.
  -- Fallback to currentPlayerIdx-derived accuser for backward compatibility
  -- with any state written before this migration.
  IF v_pending_accuser IS NULL THEN
    v_pending_accuser := v_alive->>COALESCE((v_state->>'currentPlayerIdx')::int, 0);
  END IF;

  v_winner_id := CASE
    WHEN v_pending_cause = 'lied' THEN v_pending_accuser
    ELSE v_accused_id
  END;

  IF v_outcome = 'spilled' THEN
    SELECT jsonb_agg(p_id ORDER BY ord)
    INTO v_alive
    FROM jsonb_array_elements_text(v_alive) WITH ORDINALITY AS t(p_id, ord)
    WHERE p_id <> v_pending_loser;
    v_alive := COALESCE(v_alive, '[]'::jsonb);
    v_alive_count := jsonb_array_length(v_alive);

    IF v_alive_count <= 1 THEN
      v_winner_id := v_alive->>0;
      v_wins := COALESCE(v_state->'wins', '{}'::jsonb);
      IF v_winner_id IS NOT NULL THEN
        v_wins := jsonb_set(
          v_wins,
          ARRAY[v_winner_id],
          to_jsonb(COALESCE((v_wins->>v_winner_id)::int, 0) + 1),
          true
        );
      END IF;

      v_state := v_state || jsonb_build_object(
        'alivePlayers', v_alive,
        'wins',         v_wins,
        'winnerId',     v_winner_id,
        'phase',        'result',
        'phaseStartAt', public.huddle_phase_start_ms()
      );
      v_state := jsonb_set(
        v_state,
        '{revision}',
        to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
      );
      UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
      RETURN v_state;
    END IF;

    v_cup_spills := 1;
  ELSE
    v_cup_spills := LEAST(6, COALESCE((v_state->>'cupSpills')::int, 1) + 1);
    v_alive_count := jsonb_array_length(v_alive);
  END IF;

  v_winner_idx := COALESCE(
    (SELECT ord::int - 1
     FROM jsonb_array_elements_text(v_alive) WITH ORDINALITY AS t(p_id, ord)
     WHERE p_id = v_winner_id
     LIMIT 1),
    0
  );

  v_multiplier := GREATEST(1, CEIL(v_alive_count / 4.0)::int);  -- ceil(players/4); see start_game
  WITH ranks AS (
    SELECT 'A' AS rank, generate_series(1, 6 * v_multiplier) AS n
    UNION ALL
    SELECT 'K', generate_series(1, 6 * v_multiplier)
    UNION ALL
    SELECT 'Q', generate_series(1, 6 * v_multiplier)
    UNION ALL
    SELECT 'J', generate_series(1, 2 * v_multiplier)
  )
  SELECT jsonb_agg(
    jsonb_build_object('rank', rank, 'id', lower(rank) || n)
    ORDER BY random()
  )
  INTO v_deck
  FROM ranks;

  v_prev_table := v_state->>'tableCard';
  IF v_prev_table IS NULL THEN
    v_table_card := (ARRAY['A','K','Q'])[1 + floor(random() * 3)::int];
  ELSE
    v_table_card := (
      SELECT r FROM unnest(ARRAY['A','K','Q']) r
      WHERE r <> v_prev_table
      ORDER BY random() LIMIT 1
    );
  END IF;

  v_hands := '{}'::jsonb;
  FOR v_idx IN 0 .. v_alive_count - 1 LOOP
    v_player_id := v_alive->>v_idx;
    SELECT jsonb_agg(card)
    INTO v_player_hand
    FROM (
      SELECT card
      FROM jsonb_array_elements(v_deck) WITH ORDINALITY AS t(card, ord)
      WHERE ord > v_idx * v_hand_size AND ord <= (v_idx + 1) * v_hand_size
    ) s;
    v_hands := jsonb_set(v_hands, ARRAY[v_player_id], COALESCE(v_player_hand, '[]'::jsonb));
  END LOOP;

  v_round_count := COALESCE((v_state->>'roundCount')::int, 0) + 1;

  v_state := v_state || jsonb_build_object(
    'alivePlayers',       v_alive,
    'cupSpills',          v_cup_spills,
    'roundCount',         v_round_count,
    'tableCard',          v_table_card,
    'hands',              v_hands,
    'pile',               '[]'::jsonb,
    'lastPlay',           null,
    'recentPlays',        '{}'::jsonb,
    'pendingLoserId',     null,
    'pendingLoserCause',  null,
    'pendingAccuserId',   null,
    'sipOutcome',         null,
    'sipChamberIdx',      null,
    'sipChamberIsSpill',  '[]'::jsonb,
    'sipTaken',           false,
    'nextRoundStartIdx',  null,
    'currentPlayerIdx',   v_winner_idx,
    'phase',              'tablecard',
    'phaseStartAt',       public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_call_liar(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_my_player_id     TEXT;
  v_alive            JSONB;
  v_last_play        JSONB;
  v_accused_id       TEXT;
  v_claimed_rank     TEXT;
  v_all_valid        BOOLEAN;
  v_pending_loser    TEXT;
  v_pending_cause    TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  IF (v_state->>'phase') <> 'play' THEN
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;

  v_last_play := v_state->'lastPlay';
  IF v_last_play IS NULL OR jsonb_typeof(v_last_play) <> 'object' THEN
    RAISE EXCEPTION 'no_last_play' USING ERRCODE = '42501';
  END IF;

  -- Identify caller's seat
  SELECT key INTO v_my_player_id
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_player_id IS NULL THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  -- NEW: caller must be ALIVE (still in this round) and NOT the accused
  v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
  IF NOT EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_alive) AS a(pid)
    WHERE a.pid = v_my_player_id
  ) THEN
    RAISE EXCEPTION 'not_alive' USING ERRCODE = '42501';
  END IF;

  v_accused_id := v_last_play->>'byPlayerId';
  IF v_my_player_id = v_accused_id THEN
    RAISE EXCEPTION 'cannot_call_on_self' USING ERRCODE = '42501';
  END IF;

  v_claimed_rank := v_last_play->>'claimedRank';

  -- All cards valid if every one matches claimed rank OR is a Joker
  SELECT NOT EXISTS (
    SELECT 1 FROM jsonb_array_elements(v_last_play->'cards') AS c(card)
    WHERE (card->>'rank') <> v_claimed_rank AND (card->>'rank') <> 'J'
  ) INTO v_all_valid;

  IF v_all_valid THEN
    v_pending_loser := v_my_player_id;     -- wrong accuse → CALLER goes to cup
    v_pending_cause := 'wrongAccuse';
  ELSE
    v_pending_loser := v_accused_id;       -- liar caught
    v_pending_cause := 'lied';
  END IF;

  -- NEW: store the accuser so after_sip can pick the right next-round leader
  -- regardless of whose turn it was at call time.
  v_state := v_state || jsonb_build_object(
    'pendingAccuserId',  v_my_player_id,
    'pendingLoserId',    v_pending_loser,
    'pendingLoserCause', v_pending_cause,
    'phase',             'reveal',
    'phaseStartAt',      public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_finish_solo(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid           TEXT;
  v_state         JSONB;
  v_my_seat       TEXT;
  v_alive         JSONB;
  v_wins          JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  SELECT key INTO v_my_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_seat IS NULL THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
  IF NOT EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_alive) AS a(p_id)
    WHERE p_id = v_my_seat
  ) THEN
    RAISE EXCEPTION 'not_alive' USING ERRCODE = '42501';
  END IF;

  -- Already in result phase? Idempotent.
  IF (v_state->>'phase') = 'result' THEN
    RETURN v_state;
  END IF;

  v_wins := COALESCE(v_state->'wins', '{}'::jsonb);
  v_wins := jsonb_set(
    v_wins,
    ARRAY[v_my_seat],
    to_jsonb(COALESCE((v_wins->>v_my_seat)::int, 0) + 1),
    true
  );

  v_state := v_state || jsonb_build_object(
    'alivePlayers', jsonb_build_array(v_my_seat),
    'wins',         v_wins,
    'winnerId',     v_my_seat,
    'phase',        'result',
    'phaseStartAt', public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_handle_disconnect(p_code text, p_gone_session_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_phase            TEXT;
  v_gone_seat        TEXT;
  v_pending_loser    TEXT;
  v_alive            JSONB;
  v_alive_idx        INT;
  v_current_idx      INT;
  v_new_alive        JSONB;
  v_new_alive_count  INT;
  v_n                INT;
  v_new_current      INT;
  v_chambers         JSONB;
  v_winner_id        TEXT;
  v_wins             JSONB;
  v_remaining_claim  JSONB;
  v_lowest_seat_uid  TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  v_phase := v_state->>'phase';

  -- Find the gone player's seat
  SELECT key INTO v_gone_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = p_gone_session_id
  LIMIT 1;

  IF v_gone_seat IS NULL THEN
    -- Already cleaned up; idempotent
    RETURN v_state;
  END IF;

  -- Always remove the gone seat from claimedBy
  v_remaining_claim := (v_state->'claimedBy') - v_gone_seat;
  v_state := jsonb_set(v_state, '{claimedBy}', v_remaining_claim);

  -- Transfer host if the gone player was host (lexicographic seat order,
  -- matches the client's existing rule).
  IF (v_state->>'hostId') = p_gone_session_id THEN
    SELECT value INTO v_lowest_seat_uid
    FROM jsonb_each_text(v_remaining_claim)
    ORDER BY key
    LIMIT 1;
    IF v_lowest_seat_uid IS NOT NULL THEN
      v_state := jsonb_set(v_state, '{hostId}', to_jsonb(v_lowest_seat_uid));
    ELSE
      v_state := jsonb_set(v_state, '{hostId}', 'null'::jsonb);
    END IF;
  END IF;

  -- Lobby/result/undefined: seat removal is all we needed
  IF v_phase IS NULL OR v_phase = 'lobby' OR v_phase = 'result' THEN
    v_state := jsonb_set(
      v_state,
      '{revision}',
      to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
    );
    UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
    RETURN v_state;
  END IF;

  -- === CASE A: gone player is the pendingLoser in reveal/cup ===
  v_pending_loser := v_state->>'pendingLoserId';
  IF (v_phase = 'reveal' OR v_phase = 'cup') AND v_pending_loser = v_gone_seat THEN
    -- Force-resolve as if they spilled, then run after-sip inline.
    v_chambers := COALESCE(v_state->'sipChamberIsSpill', '[]'::jsonb);
    IF jsonb_array_length(v_chambers) <> 6 THEN
      v_chambers := '[true,false,false,false,false,false]'::jsonb;
    END IF;
    -- Pick first spill chamber, or chamber 0 if no spill exists (force one).
    SELECT COALESCE(MIN(ord)::int - 1, 0)
    INTO v_alive_idx
    FROM jsonb_array_elements(v_chambers) WITH ORDINALITY AS t(elem, ord)
    WHERE elem::text::boolean = true;
    IF (v_chambers->v_alive_idx)::text::boolean IS NOT TRUE THEN
      v_chambers := jsonb_set(v_chambers, ARRAY['0'], 'true'::jsonb);
      v_alive_idx := 0;
    END IF;
    v_state := v_state || jsonb_build_object(
      'phase',             'cup',
      'sipChamberIsSpill', v_chambers,
      'sipChamberIdx',     v_alive_idx,
      'sipOutcome',        'spilled',
      'sipTaken',          true
    );

    -- Inline after_sip's "spilled" branch: eliminate loser, check win, or
    -- deal next round. (Copy of huddle_liar_after_sip logic, but the gone
    -- player IS the loser so they're auto-eliminated.)
    v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
    SELECT jsonb_agg(p_id ORDER BY ord)
    INTO v_new_alive
    FROM jsonb_array_elements_text(v_alive) WITH ORDINALITY AS t(p_id, ord)
    WHERE p_id <> v_gone_seat;
    v_new_alive := COALESCE(v_new_alive, '[]'::jsonb);
    v_new_alive_count := jsonb_array_length(v_new_alive);

    IF v_new_alive_count <= 1 THEN
      v_winner_id := v_new_alive->>0;
      v_wins := COALESCE(v_state->'wins', '{}'::jsonb);
      IF v_winner_id IS NOT NULL THEN
        v_wins := jsonb_set(
          v_wins,
          ARRAY[v_winner_id],
          to_jsonb(COALESCE((v_wins->>v_winner_id)::int, 0) + 1),
          true
        );
      END IF;
      v_state := v_state || jsonb_build_object(
        'alivePlayers', v_new_alive,
        'wins',         v_wins,
        'winnerId',     v_winner_id,
        'phase',        'result',
        'phaseStartAt', public.huddle_phase_start_ms()
      );
      v_state := jsonb_set(
        v_state,
        '{revision}',
        to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
      );
      UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
      RETURN v_state;
    END IF;

    -- Survivors > 1: dealing next round on disconnect would require full
    -- deck-deal logic. To keep this RPC bounded, set phase='tablecard'
    -- WITHOUT redealing — the next legitimate action (e.g. host) will deal
    -- via huddle_liar_after_sip's normal flow when sipTaken stays true and
    -- caller has loser claim. Simpler interim: set state ready for a manual
    -- re-deal trigger.
    --
    -- Cleaner: just remove the loser, keep phase='cup'+sipTaken so that
    -- ANY remaining claimant's device (no longer the loser, who's gone)
    -- can call huddle_liar_after_sip to advance. But after_sip requires
    -- the caller to BE the loser. Workaround: change pendingLoserId to a
    -- different player so cleanup completes. Risky.
    --
    -- Decision: inline the same deck-deal logic from huddle_liar_after_sip.
    DECLARE
      v_accuser_idx INT;
      v_accuser_id  TEXT;
      v_accused_id  TEXT;
      v_winner_idx  INT;
      v_multiplier  INT;
      v_hand_size   INT := 5;
      v_table_card  TEXT;
      v_prev_table  TEXT;
      v_deck        JSONB;
      v_hands       JSONB;
      v_player_hand JSONB;
      v_player_id   TEXT;
      v_idx         INT;
      v_round_count INT;
      v_pending_cause TEXT;
    BEGIN
      v_pending_cause := v_state->>'pendingLoserCause';
      v_accuser_idx := COALESCE((v_state->>'currentPlayerIdx')::int, 0);
      v_accuser_id := v_alive->>v_accuser_idx;
      v_accused_id := v_state->'lastPlay'->>'byPlayerId';
      v_winner_id := CASE
        WHEN v_pending_cause = 'lied' THEN v_accuser_id
        ELSE v_accused_id
      END;
      v_winner_idx := COALESCE(
        (SELECT ord::int - 1
         FROM jsonb_array_elements_text(v_new_alive) WITH ORDINALITY AS t(p_id, ord)
         WHERE p_id = v_winner_id
         LIMIT 1),
        0
      );

      v_multiplier := GREATEST(1, CEIL(v_new_alive_count / 4.0)::int);  -- ceil(players/4)
      WITH ranks AS (
        SELECT 'A' AS rank, generate_series(1, 6 * v_multiplier) AS n
        UNION ALL
        SELECT 'K', generate_series(1, 6 * v_multiplier)
        UNION ALL
        SELECT 'Q', generate_series(1, 6 * v_multiplier)
        UNION ALL
        SELECT 'J', generate_series(1, 2 * v_multiplier)
      )
      SELECT jsonb_agg(
        jsonb_build_object('rank', rank, 'id', lower(rank) || n)
        ORDER BY random()
      )
      INTO v_deck
      FROM ranks;

      v_prev_table := v_state->>'tableCard';
      IF v_prev_table IS NULL THEN
        v_table_card := (ARRAY['A','K','Q'])[1 + floor(random() * 3)::int];
      ELSE
        v_table_card := (
          SELECT r FROM unnest(ARRAY['A','K','Q']) r
          WHERE r <> v_prev_table
          ORDER BY random() LIMIT 1
        );
      END IF;

      v_hands := '{}'::jsonb;
      FOR v_idx IN 0 .. v_new_alive_count - 1 LOOP
        v_player_id := v_new_alive->>v_idx;
        SELECT jsonb_agg(card)
        INTO v_player_hand
        FROM (
          SELECT card
          FROM jsonb_array_elements(v_deck) WITH ORDINALITY AS t(card, ord)
          WHERE ord > v_idx * v_hand_size AND ord <= (v_idx + 1) * v_hand_size
        ) s;
        v_hands := jsonb_set(v_hands, ARRAY[v_player_id], COALESCE(v_player_hand, '[]'::jsonb));
      END LOOP;

      v_round_count := COALESCE((v_state->>'roundCount')::int, 0) + 1;

      v_state := v_state || jsonb_build_object(
        'alivePlayers',       v_new_alive,
        'cupSpills',          1,
        'roundCount',         v_round_count,
        'tableCard',          v_table_card,
        'hands',              v_hands,
        'pile',               '[]'::jsonb,
        'lastPlay',           null,
        'recentPlays',        '{}'::jsonb,
        'pendingLoserId',     null,
        'pendingLoserCause',  null,
        'sipOutcome',         null,
        'sipChamberIdx',      null,
        'sipChamberIsSpill',  '[]'::jsonb,
        'sipTaken',           false,
        'nextRoundStartIdx',  null,
        'currentPlayerIdx',   v_winner_idx,
        'phase',              'tablecard',
        'phaseStartAt',       public.huddle_phase_start_ms()
      );
      v_state := jsonb_set(
        v_state,
        '{revision}',
        to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
      );
      UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
      RETURN v_state;
    END;
  END IF;

  -- === CASE B: gone player is in alivePlayers during 'play' phase ===
  IF v_phase = 'play' THEN
    v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
    SELECT (ord::int - 1) INTO v_alive_idx
    FROM jsonb_array_elements_text(v_alive) WITH ORDINALITY AS t(p_id, ord)
    WHERE p_id = v_gone_seat
    LIMIT 1;

    IF v_alive_idx IS NULL THEN
      -- Already eliminated; just persist the seat clear
      v_state := jsonb_set(
        v_state,
        '{revision}',
        to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
      );
      UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
      RETURN v_state;
    END IF;

    SELECT jsonb_agg(p_id ORDER BY ord)
    INTO v_new_alive
    FROM jsonb_array_elements_text(v_alive) WITH ORDINALITY AS t(p_id, ord)
    WHERE p_id <> v_gone_seat;
    v_new_alive := COALESCE(v_new_alive, '[]'::jsonb);
    v_new_alive_count := jsonb_array_length(v_new_alive);

    IF v_new_alive_count <= 1 THEN
      v_winner_id := v_new_alive->>0;
      v_wins := COALESCE(v_state->'wins', '{}'::jsonb);
      IF v_winner_id IS NOT NULL THEN
        v_wins := jsonb_set(
          v_wins,
          ARRAY[v_winner_id],
          to_jsonb(COALESCE((v_wins->>v_winner_id)::int, 0) + 1),
          true
        );
      END IF;
      v_state := v_state || jsonb_build_object(
        'alivePlayers', v_new_alive,
        'wins',         v_wins,
        'winnerId',     v_winner_id,
        'phase',        'result',
        'phaseStartAt', public.huddle_phase_start_ms()
      );
      v_state := jsonb_set(
        v_state,
        '{revision}',
        to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
      );
      UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
      RETURN v_state;
    END IF;

    -- Normalize currentPlayerIdx (mirrors client logic)
    v_current_idx := COALESCE((v_state->>'currentPlayerIdx')::int, 0);
    v_n := v_new_alive_count;
    IF v_alive_idx < v_current_idx THEN
      v_new_current := GREATEST(0, v_current_idx - 1) % v_n;
    ELSE
      v_new_current := v_current_idx % v_n;
    END IF;

    v_state := v_state || jsonb_build_object(
      'alivePlayers',     v_new_alive,
      'currentPlayerIdx', v_new_current
    );
    v_state := jsonb_set(
      v_state,
      '{revision}',
      to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
    );
    UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
    RETURN v_state;
  END IF;

  -- Fall-through: any other phase (tablecard etc.) — just persist seat clear
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );
  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_play_again(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_players   JSONB;
  v_alive     JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);
  IF (v_state->>'phase') <> 'result' THEN
    -- Mirror client's double-tap guard
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;

  -- alivePlayers = all players (matches client liarPlayAgain line 16992)
  v_players := COALESCE(v_state->'players', '[]'::jsonb);
  SELECT jsonb_agg(p->>'id') INTO v_alive
  FROM jsonb_array_elements(v_players) p;

  v_state := v_state || jsonb_build_object(
    'alivePlayers',      COALESCE(v_alive, '[]'::jsonb),
    'cupSpills',         1,
    'roundCount',        0,
    'winnerId',          null,
    'pile',              '[]'::jsonb,
    'lastPlay',          null,
    'pendingLoserId',    null,
    'pendingLoserCause', null,
    'sipTaken',          false,
    'closedByHost',      false,
    'phase',             'lobby'
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_play_cards(p_code text, p_card_ids jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_my_player_id     TEXT;
  v_current_idx      INT;
  v_alive            JSONB;
  v_current_player   TEXT;
  v_my_hand          JSONB;
  v_card_count       INT;
  v_played_cards     JSONB;
  v_new_hand         JSONB;
  v_new_pile         JSONB;
  v_table_card       TEXT;
  v_turn_index       INT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  -- Phase guard
  IF (v_state->>'phase') <> 'play' THEN
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;

  -- Identify caller's seat from claimedBy
  SELECT key INTO v_my_player_id
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_player_id IS NULL THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;

  -- Caller must be the current player
  v_alive := COALESCE(v_state->'alivePlayers', '[]'::jsonb);
  v_current_idx := COALESCE((v_state->>'currentPlayerIdx')::int, 0);
  v_current_player := v_alive->>v_current_idx;
  IF v_current_player IS DISTINCT FROM v_my_player_id THEN
    RAISE EXCEPTION 'not_your_turn' USING ERRCODE = '42501';
  END IF;

  -- Card count guard (1-3 per Liar's Cup rules)
  IF jsonb_typeof(p_card_ids) <> 'array' THEN
    RAISE EXCEPTION 'invalid_card_ids' USING ERRCODE = '22023';
  END IF;
  v_card_count := jsonb_array_length(p_card_ids);
  IF v_card_count < 1 OR v_card_count > 3 THEN
    RAISE EXCEPTION 'card_count_out_of_range' USING ERRCODE = '22023';
  END IF;

  -- Caller's hand
  v_my_hand := COALESCE(v_state->'hands'->v_my_player_id, '[]'::jsonb);

  -- Verify EVERY requested card id is in caller's hand. This is the security
  -- linchpin — if any card id isn't present, the play is rejected wholesale.
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(p_card_ids) AS requested(id)
    WHERE NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(v_my_hand) AS held(card)
      WHERE held.card->>'id' = requested.id
    )
  ) THEN
    RAISE EXCEPTION 'card_not_in_hand' USING ERRCODE = '42501';
  END IF;

  -- Build the played-cards array (cards from hand with matching ids, in
  -- requested order). Then build the new hand (cards NOT in p_card_ids).
  SELECT jsonb_agg(card ORDER BY ord)
  INTO v_played_cards
  FROM jsonb_array_elements(v_my_hand) WITH ORDINALITY AS h(card, ord)
  WHERE card->>'id' IN (SELECT jsonb_array_elements_text(p_card_ids));

  SELECT jsonb_agg(card)
  INTO v_new_hand
  FROM jsonb_array_elements(v_my_hand) AS h(card)
  WHERE card->>'id' NOT IN (SELECT jsonb_array_elements_text(p_card_ids));

  v_new_pile := COALESCE(v_state->'pile', '[]'::jsonb) || v_played_cards;
  v_table_card := v_state->>'tableCard';
  v_turn_index := jsonb_array_length(v_new_pile);

  -- Apply mutations
  v_state := jsonb_set(v_state, ARRAY['hands', v_my_player_id], COALESCE(v_new_hand, '[]'::jsonb));
  v_state := jsonb_set(v_state, '{pile}', v_new_pile);
  v_state := jsonb_set(v_state, '{lastPlay}', jsonb_build_object(
    'count',        v_card_count,
    'cards',        v_played_cards,
    'byPlayerId',   v_my_player_id,
    'claimedRank',  v_table_card
  ));
  v_state := jsonb_set(
    v_state,
    ARRAY['recentPlays', v_my_player_id],
    jsonb_build_object(
      'count',       v_card_count,
      'claimedRank', v_table_card,
      'turnIndex',   v_turn_index
    ),
    true
  );

  -- Advance turn
  v_state := jsonb_set(
    v_state,
    '{currentPlayerIdx}',
    to_jsonb((v_current_idx + 1) % jsonb_array_length(v_alive))
  );

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_reset_players(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_my_seat   TEXT;
  v_new_claim JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  -- Find caller's seat
  SELECT key INTO v_my_seat
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;

  IF v_my_seat IS NULL THEN
    -- Host has no seat (shouldn't happen, but guard): clear claimedBy entirely
    v_new_claim := '{}'::jsonb;
  ELSE
    v_new_claim := jsonb_build_object(v_my_seat, v_uid);
  END IF;

  v_state := jsonb_set(v_state, '{claimedBy}', v_new_claim);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_start_first_turn(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid   TEXT;
  v_state JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_claimant' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'phase') <> 'tablecard' THEN
    -- Idempotent for double-taps: if already past tablecard, return current state
    RETURN v_state;
  END IF;

  v_state := v_state
    || jsonb_build_object(
      'phase',        'play',
      'phaseStartAt', public.huddle_phase_start_ms()
    );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );
  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_start_game(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid           TEXT;
  v_state         JSONB;
  v_claimedBy     JSONB;
  v_alive         JSONB;
  v_alive_count   INT;
  v_deck          JSONB;
  v_multiplier    INT;
  v_hand_size     INT := 5;
  v_table_card    TEXT;
  v_prev_table    TEXT;
  v_hands         JSONB;
  v_player_hand   JSONB;
  v_player_id     TEXT;
  v_idx           INT;
  v_start_idx     INT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_assert_host(v_state, v_uid);

  v_claimedBy := COALESCE(v_state->'claimedBy', '{}'::jsonb);
  -- alivePlayers = claimed seats only
  SELECT jsonb_agg(key ORDER BY key) INTO v_alive
  FROM jsonb_each_text(v_claimedBy);
  v_alive_count := jsonb_array_length(COALESCE(v_alive, '[]'::jsonb));
  IF v_alive_count < 2 THEN
    RAISE EXCEPTION 'need_at_least_2_players' USING ERRCODE = '42501';
  END IF;

  -- Deck multiplier (matches liarBuildDeck): ceil(players / 4) → one 20-card unit
  -- per (up to) 4 players. 2-4→1, 5-8→2, 9-12→3, 13-16→4, 17-20→5.
  v_multiplier := GREATEST(1, CEIL(v_alive_count / 4.0)::int);

  -- Build deck (6A, 6K, 6Q, 2J × multiplier)
  WITH ranks AS (
    SELECT 'A' AS rank, generate_series(1, 6 * v_multiplier) AS n
    UNION ALL
    SELECT 'K', generate_series(1, 6 * v_multiplier)
    UNION ALL
    SELECT 'Q', generate_series(1, 6 * v_multiplier)
    UNION ALL
    SELECT 'J', generate_series(1, 2 * v_multiplier)
  )
  SELECT jsonb_agg(
    jsonb_build_object('rank', rank, 'id', lower(rank) || n)
    ORDER BY random()
  )
  INTO v_deck
  FROM ranks;

  -- Pick tableCard — avoid same as previous round if possible
  v_prev_table := v_state->>'tableCard';
  IF v_prev_table IS NULL THEN
    v_table_card := (ARRAY['A','K','Q'])[1 + floor(random() * 3)::int];
  ELSE
    -- Pick from {A,K,Q} minus prev
    v_table_card := (
      SELECT r FROM unnest(ARRAY['A','K','Q']) r
      WHERE r <> v_prev_table
      ORDER BY random() LIMIT 1
    );
  END IF;

  -- Deal hands: 5 cards per alive player from the shuffled deck
  v_hands := '{}'::jsonb;
  FOR v_idx IN 0 .. v_alive_count - 1 LOOP
    v_player_id := v_alive->>v_idx;
    SELECT jsonb_agg(card)
    INTO v_player_hand
    FROM (
      SELECT card
      FROM jsonb_array_elements(v_deck) WITH ORDINALITY AS t(card, ord)
      WHERE ord > v_idx * v_hand_size AND ord <= (v_idx + 1) * v_hand_size
    ) s;
    v_hands := jsonb_set(v_hands, ARRAY[v_player_id], COALESCE(v_player_hand, '[]'::jsonb));
  END LOOP;

  -- Starting player: seat 0 (matches client default for first round)
  v_start_idx := 0;

  -- Build the new state
  v_state := v_state
    || jsonb_build_object(
      'alivePlayers',         v_alive,
      'cupSpills',            1,
      'roundCount',           1,
      'winnerId',             null,
      'tableCard',            v_table_card,
      'hands',                v_hands,
      'pile',                 '[]'::jsonb,
      'lastPlay',             null,
      'recentPlays',          '{}'::jsonb,
      'pendingLoserId',       null,
      'pendingLoserCause',    null,
      'sipOutcome',           null,
      'sipChamberIdx',        null,
      'sipChamberIsSpill',    '[]'::jsonb,
      'sipTaken',             false,
      'nextRoundStartIdx',    null,
      'currentPlayerIdx',     v_start_idx,
      'phase',                'tablecard',
      'phaseStartAt',         public.huddle_phase_start_ms()
    );

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;

  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_start_sip(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_my_player_id     TEXT;
  v_pending_loser    TEXT;
  v_spills           INT;
  v_chambers         JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  IF (v_state->>'phase') <> 'reveal' THEN
    -- Idempotent for double-fire: already past reveal, return current state
    RETURN v_state;
  END IF;

  v_pending_loser := v_state->>'pendingLoserId';
  IF v_pending_loser IS NULL THEN
    RAISE EXCEPTION 'no_pending_loser' USING ERRCODE = '42501';
  END IF;

  -- Caller must be the pending loser
  SELECT key INTO v_my_player_id
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_player_id IS DISTINCT FROM v_pending_loser THEN
    RAISE EXCEPTION 'not_loser' USING ERRCODE = '42501';
  END IF;

  -- Build chamber pattern: place `spills` true values among 6 chambers randomly.
  v_spills := GREATEST(1, LEAST(6, COALESCE((v_state->>'cupSpills')::int, 1)));

  -- Generate 6 booleans: first v_spills are true, then shuffled.
  SELECT jsonb_agg(is_spill ORDER BY random())
  INTO v_chambers
  FROM (
    SELECT (n <= v_spills) AS is_spill
    FROM generate_series(1, 6) n
  ) s;

  v_state := v_state || jsonb_build_object(
    'sipChamberIsSpill', v_chambers,
    'sipChamberIdx',     null,
    'sipOutcome',        null,
    'sipTaken',          false,
    'phase',             'cup',
    'phaseStartAt',      public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_liar_take_sip(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_my_player_id     TEXT;
  v_pending_loser    TEXT;
  v_chambers         JSONB;
  v_chamber_idx      INT;
  v_is_spill         BOOLEAN;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.liar_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  IF (v_state->>'phase') <> 'cup' THEN
    RAISE EXCEPTION 'wrong_phase: %', v_state->>'phase' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'sipTaken')::boolean IS TRUE THEN
    -- Idempotent for double-tap
    RETURN v_state;
  END IF;

  v_pending_loser := v_state->>'pendingLoserId';
  SELECT key INTO v_my_player_id
  FROM jsonb_each_text(v_state->'claimedBy')
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_player_id IS DISTINCT FROM v_pending_loser THEN
    RAISE EXCEPTION 'not_loser' USING ERRCODE = '42501';
  END IF;

  v_chambers := COALESCE(v_state->'sipChamberIsSpill', '[]'::jsonb);
  IF jsonb_array_length(v_chambers) <> 6 THEN
    RAISE EXCEPTION 'invalid_chamber_state' USING ERRCODE = '42501';
  END IF;

  v_chamber_idx := floor(random() * 6)::int;
  v_is_spill := (v_chambers->v_chamber_idx)::text::boolean;

  v_state := v_state || jsonb_build_object(
    'sipChamberIdx', v_chamber_idx,
    'sipOutcome',    CASE WHEN v_is_spill THEN 'spilled' ELSE 'safe' END,
    'sipTaken',      true,
    'phaseStartAt',  public.huddle_phase_start_ms()
  );
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.liar_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;
