-- ============================================================================
-- 07 — Mafia RPCs (canonical start_game; classic night-engine RPCs retained as live)
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tmp/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.huddle_mafia_advance_beat(p_code text, p_beat_id text, p_phase text, p_round integer DEFAULT NULL::integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_beat_id IS NULL OR length(p_beat_id) = 0 THEN
    RAISE EXCEPTION 'invalid_beat_id' USING ERRCODE = '22023';
  END IF;
  -- 'rules' added — pre-game gate where every player taps "I'm Ready"
  -- before the first narrator beat fires.
  IF p_phase NOT IN ('rules','night-mafia','night-detective','night-doctor','night-resolve',
                     'day-reveal','day-discuss','vote','vote-tie','day-eliminate','end') THEN
    RAISE EXCEPTION 'invalid_phase: %', p_phase USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  v_state := jsonb_set(v_state, '{beatId}', to_jsonb(p_beat_id));
  v_state := jsonb_set(v_state, '{phase}',  to_jsonb(p_phase));
  -- Optional round update — only set when the caller explicitly bumps the round.
  IF p_round IS NOT NULL THEN
    v_state := jsonb_set(v_state, '{round}', to_jsonb(p_round));
  END IF;
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_detective_query(p_code text, p_target text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_role      TEXT;
  v_is_mafia  BOOLEAN;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  IF (v_state->>'phase') <> 'night-detective' THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;
  IF NOT (v_state->'aliveIds') ? p_target THEN
    RAISE EXCEPTION 'target_not_alive' USING ERRCODE = '42501';
  END IF;

  -- Look up the target's role.
  SELECT role INTO v_role
  FROM public.mafia_roles
  WHERE code = p_code AND player_id = p_target;

  v_is_mafia := (v_role = 'mafia');

  -- Record the query target in public state (not the result).
  v_state := jsonb_set(v_state, '{detectiveTarget}', to_jsonb(p_target));
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;

  -- Return the result to the caller (narrator) only.
  RETURN jsonb_build_object('isMafia', v_is_mafia, 'state', v_state);
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_doctor_save(p_code text, p_target text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  IF (v_state->>'phase') <> 'night-doctor' THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;
  IF NOT (v_state->'aliveIds') ? p_target THEN
    RAISE EXCEPTION 'target_not_alive' USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{saveTarget}', to_jsonb(p_target));
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_eliminate(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_tally            JSONB;
  v_max_count        INT;
  v_max_targets      TEXT[];
  v_eliminated       TEXT;
  v_alive_arr        JSONB;
  v_dead_arr         JSONB;
  v_alive_count      INT;
  v_mafia_alive      INT;
  v_town_alive       INT;
  v_winner           TEXT;
  v_role_reveal      JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  IF (v_state->>'phase') NOT IN ('vote','vote-tie') THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;

  v_tally := COALESCE(v_state->'voteTally', '{}'::jsonb);

  SELECT COALESCE(max((value)::int), 0) INTO v_max_count
  FROM jsonb_each_text(v_tally);

  IF v_max_count = 0 THEN
    RAISE EXCEPTION 'no_votes_cast' USING ERRCODE = '42501';
  END IF;

  SELECT array_agg(key) INTO v_max_targets
  FROM jsonb_each_text(v_tally)
  WHERE (value)::int = v_max_count;

  IF array_length(v_max_targets, 1) > 1 THEN
    -- Tie. Re-vote needed.
    v_state := jsonb_set(v_state, '{phase}',     '"vote-tie"'::jsonb);
    v_state := jsonb_set(v_state, '{voteTally}', '{}'::jsonb);
    v_state := jsonb_set(v_state, '{votedBy}',   '{}'::jsonb);
    v_state := jsonb_set(v_state, '{beatId}',    '"middle-vote-tie-revote"'::jsonb);
    v_state := jsonb_set(v_state, '{tiedCandidates}', to_jsonb(v_max_targets));
    v_state := jsonb_set(
      v_state,
      '{revision}',
      to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
    );
    UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
    RETURN v_state;
  END IF;

  v_eliminated := v_max_targets[1];
  v_alive_arr := COALESCE(v_state->'aliveIds', '[]'::jsonb);
  v_dead_arr  := COALESCE(v_state->'deadIds',  '[]'::jsonb);

  SELECT jsonb_agg(elem) INTO v_alive_arr
  FROM jsonb_array_elements_text(v_alive_arr) AS elem
  WHERE elem <> v_eliminated;
  v_alive_arr := COALESCE(v_alive_arr, '[]'::jsonb);
  v_dead_arr  := v_dead_arr || to_jsonb(v_eliminated);

  SELECT count(*) INTO v_mafia_alive
  FROM public.mafia_roles
  WHERE code = p_code
    AND role = 'mafia'
    AND player_id IN (SELECT jsonb_array_elements_text(v_alive_arr));

  v_alive_count := jsonb_array_length(v_alive_arr);
  v_town_alive := v_alive_count - v_mafia_alive;

  v_winner := NULL;
  IF v_mafia_alive = 0 THEN
    v_winner := 'town';
  ELSIF v_mafia_alive >= v_town_alive THEN
    v_winner := 'mafia';
  END IF;

  v_state := jsonb_set(v_state, '{aliveIds}', v_alive_arr);
  v_state := jsonb_set(v_state, '{deadIds}',  v_dead_arr);
  v_state := jsonb_set(v_state, '{lastEliminated}', to_jsonb(v_eliminated));

  IF v_winner IS NOT NULL THEN
    SELECT jsonb_object_agg(player_id, role) INTO v_role_reveal
    FROM public.mafia_roles
    WHERE code = p_code;
    v_state := jsonb_set(v_state, '{phase}',      '"end"'::jsonb);
    v_state := jsonb_set(v_state, '{winner}',     to_jsonb(v_winner));
    v_state := jsonb_set(v_state, '{roleReveal}', COALESCE(v_role_reveal, '{}'::jsonb));
    v_state := jsonb_set(v_state, '{beatId}',     to_jsonb('endgame-win-' || v_winner));
  ELSE
    v_state := jsonb_set(v_state, '{phase}',  '"day-eliminate"'::jsonb);
    v_state := jsonb_set(v_state, '{beatId}', '"middle-vote-reveal"'::jsonb);
    v_state := jsonb_set(v_state, '{voteTally}', '{}'::jsonb);
    v_state := jsonb_set(v_state, '{votedBy}',   '{}'::jsonb);
    v_state := jsonb_set(v_state, '{tiedCandidates}', 'null'::jsonb);
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_get_my_role(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid           TEXT;
  v_state         JSONB;
  v_narrator_uid  TEXT;
  v_my_seat       TEXT;
  v_my_role       TEXT;
  v_teammates     JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT state INTO v_state FROM public.mafia_rooms WHERE code = p_code;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  v_narrator_uid := v_state->>'narratorUid';
  IF v_narrator_uid = v_uid THEN
    RETURN jsonb_build_object('role', NULL);
  END IF;

  SELECT key INTO v_my_seat
  FROM jsonb_each_text(COALESCE(v_state->'claimedBy', '{}'::jsonb))
  WHERE value = v_uid
  LIMIT 1;

  IF v_my_seat IS NULL THEN
    RETURN jsonb_build_object('role', NULL);
  END IF;

  SELECT role INTO v_my_role
  FROM public.mafia_roles
  WHERE code = p_code AND player_id = v_my_seat;

  IF v_my_role IS NULL THEN
    RETURN jsonb_build_object('role', NULL);
  END IF;

  -- Both Mafia and Mafia Leader see each other as teammates.
  IF v_my_role IN ('mafia', 'mafia_leader') THEN
    SELECT jsonb_agg(player_id) INTO v_teammates
    FROM public.mafia_roles
    WHERE code = p_code
      AND role IN ('mafia', 'mafia_leader')
      AND player_id <> v_my_seat;
    RETURN jsonb_build_object('role', v_my_role, 'teammates', COALESCE(v_teammates, '[]'::jsonb));
  END IF;

  RETURN jsonb_build_object('role', v_my_role);
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_get_narrator_state(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
  v_roles  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  SELECT state INTO v_state FROM public.mafia_rooms WHERE code = p_code;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  SELECT jsonb_object_agg(player_id, role) INTO v_roles
  FROM public.mafia_roles
  WHERE code = p_code;

  RETURN jsonb_build_object('roles', COALESCE(v_roles, '{}'::jsonb));
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_handle_disconnect(p_code text, p_player_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_target_uid       TEXT;
  v_claimedBy        JSONB;
  v_alive_arr        JSONB;
  v_dead_arr         JSONB;
  v_alive_count      INT;
  v_mafia_alive      INT;
  v_town_alive       INT;
  v_winner           TEXT;
  v_role_reveal      JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  v_target_uid := v_state->'claimedBy'->>p_player_id;
  IF v_target_uid IS NULL THEN
    -- Already gone. Idempotent.
    RETURN v_state;
  END IF;

  -- Authz: either narrator OR the disconnecting player themselves.
  IF v_uid <> v_target_uid AND v_uid <> (v_state->>'narratorUid') THEN
    RAISE EXCEPTION 'not_authorized' USING ERRCODE = '42501';
  END IF;

  IF (v_state->>'phase') = 'lobby' THEN
    -- Lobby: free the seat.
    v_claimedBy := v_state->'claimedBy' - p_player_id;
    v_state := jsonb_set(v_state, '{claimedBy}', v_claimedBy);
    -- If they were the narrator, clear narratorUid.
    IF v_target_uid = (v_state->>'narratorUid') THEN
      v_state := jsonb_set(v_state, '{narratorUid}', 'null'::jsonb);
    END IF;
  ELSE
    -- Mid-game: mark as dead if alive.
    v_alive_arr := COALESCE(v_state->'aliveIds', '[]'::jsonb);
    v_dead_arr  := COALESCE(v_state->'deadIds',  '[]'::jsonb);
    IF v_alive_arr ? p_player_id THEN
      SELECT jsonb_agg(elem) INTO v_alive_arr
      FROM jsonb_array_elements_text(v_alive_arr) AS elem
      WHERE elem <> p_player_id;
      v_alive_arr := COALESCE(v_alive_arr, '[]'::jsonb);
      v_dead_arr  := v_dead_arr || to_jsonb(p_player_id);
      v_state := jsonb_set(v_state, '{aliveIds}', v_alive_arr);
      v_state := jsonb_set(v_state, '{deadIds}',  v_dead_arr);

      -- Re-check win condition.
      SELECT count(*) INTO v_mafia_alive
      FROM public.mafia_roles
      WHERE code = p_code
        AND role = 'mafia'
        AND player_id IN (SELECT jsonb_array_elements_text(v_alive_arr));
      v_alive_count := jsonb_array_length(v_alive_arr);
      v_town_alive := v_alive_count - v_mafia_alive;

      v_winner := NULL;
      IF v_mafia_alive = 0 THEN
        v_winner := 'town';
      ELSIF v_mafia_alive >= v_town_alive THEN
        v_winner := 'mafia';
      END IF;

      IF v_winner IS NOT NULL THEN
        SELECT jsonb_object_agg(player_id, role) INTO v_role_reveal
        FROM public.mafia_roles WHERE code = p_code;
        v_state := jsonb_set(v_state, '{phase}',      '"end"'::jsonb);
        v_state := jsonb_set(v_state, '{winner}',     to_jsonb(v_winner));
        v_state := jsonb_set(v_state, '{roleReveal}', COALESCE(v_role_reveal, '{}'::jsonb));
        v_state := jsonb_set(v_state, '{beatId}',     to_jsonb('end-' || v_winner));
      END IF;
    END IF;
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_mafia_kill(p_code text, p_target text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  IF (v_state->>'phase') <> 'night-mafia' THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;
  IF NOT (v_state->'aliveIds') ? p_target THEN
    RAISE EXCEPTION 'target_not_alive' USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{killTarget}', to_jsonb(p_target));
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_play_again(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'hostId') IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'not_host' USING ERRCODE = '42501';
  END IF;

  -- Clear roles.
  DELETE FROM public.mafia_roles WHERE code = p_code;

  -- Reset state (keep claimedBy, hostId, narratorUid).
  v_state := jsonb_set(v_state, '{phase}',           '"lobby"'::jsonb);
  v_state := jsonb_set(v_state, '{round}',           '0'::jsonb);
  v_state := jsonb_set(v_state, '{aliveIds}',        '[]'::jsonb);
  v_state := jsonb_set(v_state, '{deadIds}',         '[]'::jsonb);
  v_state := jsonb_set(v_state, '{killTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{saveTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{detectiveTarget}', 'null'::jsonb);
  v_state := jsonb_set(v_state, '{voteTally}',       '{}'::jsonb);
  v_state := jsonb_set(v_state, '{votedBy}',         '{}'::jsonb);
  v_state := jsonb_set(v_state, '{tiedCandidates}',  'null'::jsonb);
  v_state := jsonb_set(v_state, '{lastEliminated}',  'null'::jsonb);
  v_state := jsonb_set(v_state, '{beatId}',          '"lobby"'::jsonb);
  v_state := jsonb_set(v_state, '{winner}',          'null'::jsonb);
  v_state := jsonb_set(v_state, '{roleReveal}',      '{}'::jsonb);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_record_vote(p_code text, p_target text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid       TEXT;
  v_state     JSONB;
  v_my_seat   TEXT;
  v_tally     JSONB;
  v_voted_by  JSONB;
  v_old_count INT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  IF (v_state->>'phase') NOT IN ('vote','vote-tie') THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;

  -- Find caller's seat.
  SELECT key INTO v_my_seat
  FROM jsonb_each_text(COALESCE(v_state->'claimedBy', '{}'::jsonb))
  WHERE value = v_uid
  LIMIT 1;
  IF v_my_seat IS NULL THEN
    RAISE EXCEPTION 'not_seated' USING ERRCODE = '42501';
  END IF;
  IF NOT (v_state->'aliveIds') ? v_my_seat THEN
    RAISE EXCEPTION 'voter_not_alive' USING ERRCODE = '42501';
  END IF;
  IF v_my_seat = p_target THEN
    RAISE EXCEPTION 'cant_vote_self' USING ERRCODE = '42501';
  END IF;
  IF NOT (v_state->'aliveIds') ? p_target THEN
    RAISE EXCEPTION 'target_not_alive' USING ERRCODE = '42501';
  END IF;
  -- During a tie re-vote, the target must be one of the tied candidates.
  IF (v_state->>'phase') = 'vote-tie'
     AND jsonb_typeof(v_state->'tiedCandidates') = 'array'
     AND NOT (v_state->'tiedCandidates') ? p_target THEN
    RAISE EXCEPTION 'target_not_in_tie' USING ERRCODE = '42501';
  END IF;
  IF (v_state->'votedBy') ? v_uid THEN
    RAISE EXCEPTION 'already_voted' USING ERRCODE = '42501';
  END IF;

  -- Increment tally for target.
  v_tally := COALESCE(v_state->'voteTally', '{}'::jsonb);
  v_old_count := COALESCE((v_tally->>p_target)::int, 0);
  v_tally := jsonb_set(v_tally, ARRAY[p_target], to_jsonb(v_old_count + 1), true);

  -- Record who voted for whom (cleared on eliminate).
  v_voted_by := COALESCE(v_state->'votedBy', '{}'::jsonb);
  v_voted_by := jsonb_set(v_voted_by, ARRAY[v_uid], to_jsonb(p_target), true);

  v_state := jsonb_set(v_state, '{voteTally}', v_tally);
  v_state := jsonb_set(v_state, '{votedBy}',   v_voted_by);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_regenerate_room(p_old_code text, p_new_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;
  IF p_new_code IS NULL OR length(p_new_code) = 0 THEN
    RAISE EXCEPTION 'invalid_new_code' USING ERRCODE = '22023';
  END IF;
  IF p_old_code = p_new_code THEN
    RAISE EXCEPTION 'same_code' USING ERRCODE = '22023';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_old_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_old_code USING ERRCODE = 'P0002';
  END IF;
  IF NOT public.huddle_is_claimant(v_state->'claimedBy', v_uid) THEN
    RAISE EXCEPTION 'not_in_room' USING ERRCODE = '42501';
  END IF;

  -- Check new code is free.
  IF EXISTS (SELECT 1 FROM public.mafia_rooms WHERE code = p_new_code) THEN
    RAISE EXCEPTION 'new_code_in_use' USING ERRCODE = '23505';
  END IF;

  -- Use UPDATE on PK — FK on mafia_roles cascades automatically (ON UPDATE
  -- CASCADE is the default for FK PRIMARY KEY references on Postgres when
  -- declared without ON UPDATE; defensively re-key mafia_roles too).
  UPDATE public.mafia_roles SET code = p_new_code WHERE code = p_old_code;
  UPDATE public.mafia_rooms SET code = p_new_code WHERE code = p_old_code;

  SELECT state INTO v_state FROM public.mafia_rooms WHERE code = p_new_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_reset_to_lobby(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;

  -- Only the narrator may end the game. Helper raises 42501 if not narrator.
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  -- Wipe per-game role assignments. Next start_game re-deals from scratch.
  DELETE FROM public.mafia_roles WHERE code = p_code;

  -- Reset all transient game state. Keep the identity of who's in the
  -- room (claimedBy + narratorUid + hostId) so the group can immediately
  -- start a new game without re-claiming seats.
  v_state := jsonb_set(v_state, '{phase}',           '"lobby"'::jsonb);
  v_state := jsonb_set(v_state, '{beatId}',          '"lobby"'::jsonb);
  v_state := jsonb_set(v_state, '{round}',           '0'::jsonb);
  v_state := jsonb_set(v_state, '{aliveIds}',        '[]'::jsonb);
  v_state := jsonb_set(v_state, '{deadIds}',         '[]'::jsonb);
  v_state := jsonb_set(v_state, '{killTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{saveTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{detectiveTarget}', 'null'::jsonb);
  v_state := jsonb_set(v_state, '{voteTally}',       '{}'::jsonb);
  v_state := jsonb_set(v_state, '{votedBy}',         '{}'::jsonb);
  v_state := jsonb_set(v_state, '{readyBy}',         '{}'::jsonb);
  v_state := jsonb_set(v_state, '{winner}',          'null'::jsonb);
  v_state := jsonb_set(v_state, '{roleReveal}',      '{}'::jsonb);
  v_state := jsonb_set(v_state, '{lastKilled}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{lastEliminated}',  'null'::jsonb);
  v_state := jsonb_set(v_state, '{tiedCandidates}',  '[]'::jsonb);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_resolve_night(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_kill             TEXT;
  v_save             TEXT;
  v_alive_arr        JSONB;
  v_dead_arr         JSONB;
  v_alive_count      INT;
  v_mafia_alive      INT;
  v_town_alive       INT;
  v_winner           TEXT;
  v_role_reveal      JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  v_kill := v_state->>'killTarget';
  v_save := v_state->>'saveTarget';

  v_alive_arr := COALESCE(v_state->'aliveIds', '[]'::jsonb);
  v_dead_arr  := COALESCE(v_state->'deadIds',  '[]'::jsonb);

  IF (v_state->>'round')::int = 1 THEN
    v_kill := NULL;
  END IF;

  IF v_kill IS NOT NULL AND v_kill <> COALESCE(v_save, '') THEN
    SELECT jsonb_agg(elem) INTO v_alive_arr
    FROM jsonb_array_elements_text(v_alive_arr) AS elem
    WHERE elem <> v_kill;
    v_alive_arr := COALESCE(v_alive_arr, '[]'::jsonb);
    v_dead_arr := v_dead_arr || to_jsonb(v_kill);
  END IF;

  v_state := jsonb_set(v_state, '{killTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{saveTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{detectiveTarget}', 'null'::jsonb);
  v_state := jsonb_set(v_state, '{aliveIds}',        v_alive_arr);
  v_state := jsonb_set(v_state, '{deadIds}',         v_dead_arr);

  SELECT count(*) INTO v_mafia_alive
  FROM public.mafia_roles
  WHERE code = p_code
    AND role = 'mafia'
    AND player_id IN (SELECT jsonb_array_elements_text(v_alive_arr));

  v_alive_count := jsonb_array_length(v_alive_arr);
  v_town_alive := v_alive_count - v_mafia_alive;

  v_winner := NULL;
  IF v_mafia_alive = 0 THEN
    v_winner := 'town';
  ELSIF v_mafia_alive >= v_town_alive THEN
    v_winner := 'mafia';
  END IF;

  IF v_winner IS NOT NULL THEN
    SELECT jsonb_object_agg(player_id, role) INTO v_role_reveal
    FROM public.mafia_roles
    WHERE code = p_code;

    v_state := jsonb_set(v_state, '{phase}',      '"end"'::jsonb);
    v_state := jsonb_set(v_state, '{winner}',     to_jsonb(v_winner));
    v_state := jsonb_set(v_state, '{roleReveal}', COALESCE(v_role_reveal, '{}'::jsonb));
    v_state := jsonb_set(v_state, '{beatId}',     to_jsonb('endgame-win-' || v_winner));
  ELSE
    v_state := jsonb_set(v_state, '{phase}',  '"day-reveal"'::jsonb);
    v_state := jsonb_set(v_state, '{beatId}', '"middle-day-reveal"'::jsonb);
    v_state := jsonb_set(v_state, '{lastKilled}', COALESCE(to_jsonb(
      CASE WHEN v_kill IS NOT NULL AND v_kill <> COALESCE(v_save, '') THEN v_kill END
    ), 'null'::jsonb));
    v_state := jsonb_set(v_state, '{lastSaved}', COALESCE(to_jsonb(v_save), 'null'::jsonb));
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_set_narrator(p_code text, p_narrator_seat text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid          TEXT;
  v_state        JSONB;
  v_target_uid   TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'hostId') IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'not_host' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'phase') <> 'lobby' THEN
    RAISE EXCEPTION 'narrator_locked_after_start' USING ERRCODE = '42501';
  END IF;

  -- Validate target is a claimant.
  v_target_uid := v_state->'claimedBy'->>p_narrator_seat;
  IF v_target_uid IS NULL THEN
    RAISE EXCEPTION 'narrator_seat_not_claimed: %', p_narrator_seat USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{narratorUid}', to_jsonb(v_target_uid));
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_set_ready(p_code text, p_seat text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid          TEXT;
  v_state        JSONB;
  v_narrator_uid TEXT;
  v_seat_key     TEXT;
  v_ready_by     JSONB;
  v_player_seats TEXT[];
  v_all_ready    BOOLEAN;
  s              TEXT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'phase') <> 'rules' THEN
    RAISE EXCEPTION 'not_in_rules_phase' USING ERRCODE = '42501';
  END IF;

  -- Derive seat key from auth.uid(). The narrator gets a sentinel key so
  -- it counts as a distinct "slot" from any player seat.
  v_narrator_uid := v_state->>'narratorUid';
  IF v_narrator_uid = v_uid THEN
    v_seat_key := '__narrator__';
  ELSE
    SELECT key INTO v_seat_key
    FROM jsonb_each_text(COALESCE(v_state->'claimedBy', '{}'::jsonb))
    WHERE value = v_uid
    LIMIT 1;
  END IF;
  IF v_seat_key IS NULL THEN
    RAISE EXCEPTION 'caller_not_in_room' USING ERRCODE = '42501';
  END IF;

  -- Flip caller's ready bit.
  v_ready_by := COALESCE(v_state->'readyBy', '{}'::jsonb);
  v_ready_by := jsonb_set(v_ready_by, ARRAY[v_seat_key], 'true'::jsonb);
  v_state := jsonb_set(v_state, '{readyBy}', v_ready_by);

  -- Compute "all ready" = every player seat AND the narrator are true.
  SELECT array_agg(key) INTO v_player_seats
  FROM jsonb_each_text(COALESCE(v_state->'claimedBy', '{}'::jsonb))
  WHERE value <> COALESCE(v_narrator_uid, '');

  v_all_ready := TRUE;
  IF v_player_seats IS NOT NULL THEN
    FOREACH s IN ARRAY v_player_seats LOOP
      IF NOT COALESCE((v_ready_by->>s)::boolean, FALSE) THEN
        v_all_ready := FALSE;
        EXIT;
      END IF;
    END LOOP;
  END IF;
  IF v_all_ready AND v_narrator_uid IS NOT NULL THEN
    IF NOT COALESCE((v_ready_by->>'__narrator__')::boolean, FALSE) THEN
      v_all_ready := FALSE;
    END IF;
  END IF;

  IF v_all_ready THEN
    -- Gate open. Skip opening-setup + opening-roles (their content lives
    -- on the rules page) and jump straight to the first live cue.
    v_state := jsonb_set(v_state, '{phase}',  '"night-mafia"'::jsonb);
    v_state := jsonb_set(v_state, '{beatId}', '"opening-night1-open"'::jsonb);
  END IF;

  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

-- huddle_mafia_start_game: canonical 5-arg form ONLY. The stray 1-arg
-- overload (huddle_mafia_start_game(text)) is intentionally OMITTED here and
-- dropped by 09_drop_legacy.sql to resolve the live PGRST203 ambiguity.
CREATE OR REPLACE FUNCTION public.huddle_mafia_start_game(p_code text, p_include_detective boolean DEFAULT true, p_include_child boolean DEFAULT false, p_include_mafia_leader boolean DEFAULT false, p_variant text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid              TEXT;
  v_state            JSONB;
  v_narrator_uid     TEXT;
  v_player_seats     TEXT[];
  v_player_count     INT;
  v_roles            TEXT[];
  v_mafia_count      INT;
  v_villager_count   INT;
  v_alive_arr        JSONB;
  v_include_det      BOOLEAN;
  v_include_child    BOOLEAN;
  v_include_leader   BOOLEAN;
  i                  INT;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  -- COALESCE protects against explicit NULL pass (treat as default).
  v_include_det    := COALESCE(p_include_detective,    TRUE);
  v_include_child  := COALESCE(p_include_child,        FALSE);
  v_include_leader := COALESCE(p_include_mafia_leader, FALSE);

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  IF (v_state->>'hostId') IS DISTINCT FROM v_uid THEN
    RAISE EXCEPTION 'not_host' USING ERRCODE = '42501';
  END IF;
  IF (v_state->>'phase') <> 'lobby' THEN
    RAISE EXCEPTION 'already_started' USING ERRCODE = '42501';
  END IF;

  v_narrator_uid := v_state->>'narratorUid';
  IF v_narrator_uid IS NULL THEN
    RAISE EXCEPTION 'narrator_not_set' USING ERRCODE = '42501';
  END IF;

  SELECT array_agg(key ORDER BY random()) INTO v_player_seats
  FROM jsonb_each_text(COALESCE(v_state->'claimedBy', '{}'::jsonb))
  WHERE value <> v_narrator_uid;

  v_player_count := COALESCE(array_length(v_player_seats, 1), 0);
  IF v_player_count < 5 OR v_player_count > 8 THEN
    RAISE EXCEPTION 'invalid_player_count: %', v_player_count USING ERRCODE = '42501';
  END IF;

  -- Base role mix.
  IF v_player_count = 5 THEN
    v_mafia_count := 1;
    v_villager_count := 2;
  ELSIF v_player_count = 6 THEN
    v_mafia_count := 1;
    v_villager_count := 3;
  ELSIF v_player_count = 7 THEN
    v_mafia_count := 2;
    v_villager_count := 3;
  ELSE  -- 8
    v_mafia_count := 2;
    v_villager_count := 4;
  END IF;

  -- Detective slot → extra Villager when toggle is off.
  IF NOT v_include_det THEN
    v_villager_count := v_villager_count + 1;
  END IF;

  -- Mafia Leader steals ONE Mafia slot (kept on the Mafia team — same evil
  -- count, just one of them is the Godfather). Guard against under-counting:
  -- min mafia after the steal is 0, which is fine — the Leader IS evil.
  IF v_include_leader AND v_mafia_count > 0 THEN
    v_mafia_count := v_mafia_count - 1;
  END IF;

  -- Child steals ONE Villager slot. Guard against under-counting: if for some
  -- reason villager_count is already 0 (only possible with weird future
  -- toggle combos), drop the child rather than going negative.
  IF v_include_child AND v_villager_count > 0 THEN
    v_villager_count := v_villager_count - 1;
  END IF;

  -- Build role queue: Mafia(s), Mafia Leader?, Doctor, Detective?, Child?,
  -- Villager(s). Order doesn't matter for assignment (seats are shuffled
  -- above) but keeping a stable shape makes the queue easy to reason about.
  v_roles := ARRAY[]::TEXT[];
  FOR i IN 1..v_mafia_count LOOP
    v_roles := array_append(v_roles, 'mafia');
  END LOOP;
  IF v_include_leader AND
     -- Only add the Leader slot if there WAS a Mafia slot to steal.
     -- (Defends against a future role-mix table where mafia_count starts at 0.)
     v_player_count >= 5
  THEN
    v_roles := array_append(v_roles, 'mafia_leader');
  END IF;
  v_roles := array_append(v_roles, 'doctor');
  IF v_include_det THEN
    v_roles := array_append(v_roles, 'detective');
  END IF;
  IF v_include_child THEN
    v_roles := array_append(v_roles, 'child');
  END IF;
  FOR i IN 1..v_villager_count LOOP
    v_roles := array_append(v_roles, 'villager');
  END LOOP;

  IF array_length(v_player_seats, 1) <> array_length(v_roles, 1) THEN
    RAISE EXCEPTION 'role_count_mismatch: seats=% roles=%',
      array_length(v_player_seats, 1), array_length(v_roles, 1)
      USING ERRCODE = 'P0001';
  END IF;

  DELETE FROM public.mafia_roles WHERE code = p_code;

  FOR i IN 1..array_length(v_player_seats, 1) LOOP
    INSERT INTO public.mafia_roles(code, player_id, role)
    VALUES (p_code, v_player_seats[i], v_roles[i]);
  END LOOP;

  SELECT jsonb_agg(s) INTO v_alive_arr FROM unnest(v_player_seats) AS s;

  -- Rules-gate landing (unchanged from optional_roles.sql).
  v_state := jsonb_set(v_state, '{phase}',           '"rules"'::jsonb);
  v_state := jsonb_set(v_state, '{round}',           '1'::jsonb);
  v_state := jsonb_set(v_state, '{aliveIds}',        v_alive_arr);
  v_state := jsonb_set(v_state, '{deadIds}',         '[]'::jsonb);
  v_state := jsonb_set(v_state, '{killTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{saveTarget}',      'null'::jsonb);
  v_state := jsonb_set(v_state, '{detectiveTarget}', 'null'::jsonb);
  v_state := jsonb_set(v_state, '{voteTally}',       '{}'::jsonb);
  v_state := jsonb_set(v_state, '{votedBy}',         '{}'::jsonb);
  v_state := jsonb_set(v_state, '{beatId}',          '"rules-gate"'::jsonb);
  v_state := jsonb_set(v_state, '{readyBy}',         '{}'::jsonb);
  v_state := jsonb_set(v_state, '{winner}',          'null'::jsonb);
  v_state := jsonb_set(v_state, '{roleReveal}',      '{}'::jsonb);
  IF p_variant IS NOT NULL THEN
    v_state := jsonb_set(v_state, '{variant}', to_jsonb(p_variant));
  END IF;
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;

CREATE OR REPLACE FUNCTION public.huddle_mafia_start_vote(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE
  v_uid    TEXT;
  v_state  JSONB;
BEGIN
  v_uid := auth.uid()::text;
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated' USING ERRCODE = '28000';
  END IF;

  EXECUTE 'SELECT state FROM public.mafia_rooms WHERE code = $1 FOR UPDATE'
    USING p_code INTO v_state;
  IF v_state IS NULL THEN
    RAISE EXCEPTION 'room_not_found: %', p_code USING ERRCODE = 'P0002';
  END IF;
  PERFORM public.huddle_mafia_assert_narrator(v_state, v_uid);

  IF (v_state->>'phase') NOT IN ('day-discuss','day-reveal') THEN
    RAISE EXCEPTION 'wrong_phase' USING ERRCODE = '42501';
  END IF;

  v_state := jsonb_set(v_state, '{phase}',     '"vote"'::jsonb);
  v_state := jsonb_set(v_state, '{voteTally}', '{}'::jsonb);
  v_state := jsonb_set(v_state, '{votedBy}',   '{}'::jsonb);
  v_state := jsonb_set(v_state, '{beatId}',    '"middle-vote-progress"'::jsonb);
  v_state := jsonb_set(v_state, '{tiedCandidates}', 'null'::jsonb);
  v_state := jsonb_set(
    v_state,
    '{revision}',
    to_jsonb(COALESCE((v_state->>'revision')::int, 0) + 1)
  );

  UPDATE public.mafia_rooms SET state = v_state WHERE code = p_code;
  RETURN v_state;
END;
$function$;


