-- ============================================================================
-- 08 — Admin analytics
-- ----------------------------------------------------------------------------
-- Source of truth: LIVE Supabase DB (pg_get_functiondef dump, 2026-06-23).
-- Generated by tmp/build-migration-set.js — do not hand-edit; regenerate.
-- Apply in filename order on a fresh database. Idempotent (CREATE OR REPLACE).
-- ============================================================================

CREATE OR REPLACE FUNCTION public.admin_stats(p_period text DEFAULT '7d'::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  v_now           timestamptz := now();
  v_period_secs   bigint;
  v_cur_start     timestamptz;
  v_prev_start    timestamptz;
  v_bucket_secs   numeric;

  v_active_cur    integer;
  v_active_prev   integer;
  v_active_trend  integer[];

  v_signups_cur   integer;
  v_signups_prev  integer;
  v_signups_trend integer[];

  v_lobbies_cur   integer;
  v_lobbies_prev  integer;
  v_lobbies_trend integer[];

  v_played_cur    integer;
  v_played_prev   integer;
  v_played_trend  integer[];

  v_fb_cur        integer;
  v_fb_prev       integer;
  v_fb_trend      integer[];

  v_by_game       jsonb;
begin
  -- HARD GATE — only admins can run this. Returns a SQL error that the
  -- client surfaces; the data never reaches a non-admin.
  if not public.is_admin() then
    raise exception 'Not authorised' using errcode = '42501';
  end if;

  -- Resolve period
  v_period_secs := case p_period
    when '24h' then 24 * 3600
    when '7d'  then 7 * 86400
    when '30d' then 30 * 86400
    else 7 * 86400
  end;
  v_cur_start   := v_now - make_interval(secs => v_period_secs);
  v_prev_start  := v_cur_start - make_interval(secs => v_period_secs);
  v_bucket_secs := v_period_secs::numeric / 7;

  -- ====================================================================
  -- Metric 1 — Active players (distinct host_id across 4 game tables)
  -- ====================================================================
  with all_hosts as (
    select state->>'hostId' as host_id, created_at from public.hotseat_rooms
      where created_at >= v_prev_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.chameleon_rooms
      where created_at >= v_prev_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.liar_rooms
      where created_at >= v_prev_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.mafia_rooms
      where created_at >= v_prev_start and state->>'hostId' is not null
  )
  select
    count(distinct host_id) filter (where created_at >= v_cur_start),
    count(distinct host_id) filter (where created_at <  v_cur_start)
  into v_active_cur, v_active_prev
  from all_hosts;

  with all_hosts_cur as (
    select state->>'hostId' as host_id, created_at from public.hotseat_rooms
      where created_at >= v_cur_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.chameleon_rooms
      where created_at >= v_cur_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.liar_rooms
      where created_at >= v_cur_start and state->>'hostId' is not null
    union all
    select state->>'hostId',             created_at from public.mafia_rooms
      where created_at >= v_cur_start and state->>'hostId' is not null
  ),
  bucketed as (
    select least(6, floor(extract(epoch from (created_at - v_cur_start)) / v_bucket_secs)::int) as idx,
           host_id
    from all_hosts_cur
  )
  select array_agg(coalesce(c.c, 0) order by b.idx)
  into v_active_trend
  from generate_series(0, 6) as b(idx)
  left join (
    select idx, count(distinct host_id) as c from bucketed group by idx
  ) c using (idx);

  -- ====================================================================
  -- Metric 2 — Signups (real users only; anonymous sessions excluded
  -- by filtering email IS NOT NULL — works across all Supabase versions)
  -- ====================================================================
  select
    count(*) filter (where created_at >= v_cur_start),
    count(*) filter (where created_at <  v_cur_start)
  into v_signups_cur, v_signups_prev
  from auth.users
  where created_at >= v_prev_start
    and email is not null;

  with signups_cur as (
    select created_at from auth.users
    where created_at >= v_cur_start and email is not null
  )
  select array_agg(coalesce(c.c, 0) order by b.idx)
  into v_signups_trend
  from generate_series(0, 6) as b(idx)
  left join (
    select least(6, floor(extract(epoch from (created_at - v_cur_start)) / v_bucket_secs)::int) as idx,
           count(*) as c
    from signups_cur group by 1
  ) c using (idx);

  -- ====================================================================
  -- Metric 3 — Lobbies created (sum across 4 game tables)
  -- ====================================================================
  with all_lobbies as (
    select created_at from public.hotseat_rooms   where created_at >= v_prev_start
    union all
    select created_at from public.chameleon_rooms where created_at >= v_prev_start
    union all
    select created_at from public.liar_rooms      where created_at >= v_prev_start
    union all
    select created_at from public.mafia_rooms     where created_at >= v_prev_start
  )
  select
    count(*) filter (where created_at >= v_cur_start),
    count(*) filter (where created_at <  v_cur_start)
  into v_lobbies_cur, v_lobbies_prev
  from all_lobbies;

  with lobbies_cur as (
    select created_at from public.hotseat_rooms   where created_at >= v_cur_start
    union all
    select created_at from public.chameleon_rooms where created_at >= v_cur_start
    union all
    select created_at from public.liar_rooms      where created_at >= v_cur_start
    union all
    select created_at from public.mafia_rooms     where created_at >= v_cur_start
  )
  select array_agg(coalesce(c.c, 0) order by b.idx)
  into v_lobbies_trend
  from generate_series(0, 6) as b(idx)
  left join (
    select least(6, floor(extract(epoch from (created_at - v_cur_start)) / v_bucket_secs)::int) as idx,
           count(*) as c
    from lobbies_cur group by 1
  ) c using (idx);

  -- ====================================================================
  -- Metric 4 — Games actually played
  --   (lobbies where the JSONB flag _gamesPlayedCounted is true —
  --    means at least one round was played, not just lobby-then-abandon)
  -- ====================================================================
  with all_played as (
    select created_at from public.hotseat_rooms
      where created_at >= v_prev_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.chameleon_rooms
      where created_at >= v_prev_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.liar_rooms
      where created_at >= v_prev_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.mafia_rooms
      where created_at >= v_prev_start and (state->>'_gamesPlayedCounted')::boolean is true
  )
  select
    count(*) filter (where created_at >= v_cur_start),
    count(*) filter (where created_at <  v_cur_start)
  into v_played_cur, v_played_prev
  from all_played;

  with played_cur as (
    select created_at from public.hotseat_rooms
      where created_at >= v_cur_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.chameleon_rooms
      where created_at >= v_cur_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.liar_rooms
      where created_at >= v_cur_start and (state->>'_gamesPlayedCounted')::boolean is true
    union all
    select created_at from public.mafia_rooms
      where created_at >= v_cur_start and (state->>'_gamesPlayedCounted')::boolean is true
  )
  select array_agg(coalesce(c.c, 0) order by b.idx)
  into v_played_trend
  from generate_series(0, 6) as b(idx)
  left join (
    select least(6, floor(extract(epoch from (created_at - v_cur_start)) / v_bucket_secs)::int) as idx,
           count(*) as c
    from played_cur group by 1
  ) c using (idx);

  -- ====================================================================
  -- Metric 5 — Feedback received
  -- ====================================================================
  select
    count(*) filter (where created_at >= v_cur_start),
    count(*) filter (where created_at <  v_cur_start)
  into v_fb_cur, v_fb_prev
  from public.feedback_posts
  where created_at >= v_prev_start;

  with fb_cur as (
    select created_at from public.feedback_posts where created_at >= v_cur_start
  )
  select array_agg(coalesce(c.c, 0) order by b.idx)
  into v_fb_trend
  from generate_series(0, 6) as b(idx)
  left join (
    select least(6, floor(extract(epoch from (created_at - v_cur_start)) / v_bucket_secs)::int) as idx,
           count(*) as c
    from fb_cur group by 1
  ) c using (idx);

  -- ====================================================================
  -- Per-game breakdown (current period only — share of total lobbies)
  -- ====================================================================
  v_by_game := jsonb_build_object(
    'hotseat',   (select count(*) from public.hotseat_rooms   where created_at >= v_cur_start),
    'chameleon', (select count(*) from public.chameleon_rooms where created_at >= v_cur_start),
    'liar',      (select count(*) from public.liar_rooms      where created_at >= v_cur_start),
    'mafia',     (select count(*) from public.mafia_rooms     where created_at >= v_cur_start)
  );

  -- ====================================================================
  -- Assemble + return
  -- ====================================================================
  return jsonb_build_object(
    'period',          p_period,
    'generated_at',    v_now,
    'current_start',   v_cur_start,
    'previous_start',  v_prev_start,
    'active_players',  jsonb_build_object('current', v_active_cur,  'previous', v_active_prev,  'trend', coalesce(v_active_trend,  array[0,0,0,0,0,0,0])),
    'signups',         jsonb_build_object('current', v_signups_cur, 'previous', v_signups_prev, 'trend', coalesce(v_signups_trend, array[0,0,0,0,0,0,0])),
    'lobbies',         jsonb_build_object('current', v_lobbies_cur, 'previous', v_lobbies_prev, 'trend', coalesce(v_lobbies_trend, array[0,0,0,0,0,0,0])),
    'games_played',    jsonb_build_object('current', v_played_cur,  'previous', v_played_prev,  'trend', coalesce(v_played_trend,  array[0,0,0,0,0,0,0])),
    'feedback',        jsonb_build_object('current', v_fb_cur,      'previous', v_fb_prev,      'trend', coalesce(v_fb_trend,      array[0,0,0,0,0,0,0])),
    'by_game',         v_by_game
  );
end;
$function$;
